module UI.Tutorial where

tutorialText :: String
tutorialText = unlines
  [ "************************************************"
  , ""
  , "     Welcome to Vim with training wheels!"
  , ""
  , "************************************************"
  , ""
  , "This editor will help you get to know basic "
  , "Vim functionality in a training environment. "
  , ""
  , "************************************************"
  , "# How to use this tutorial"
  , ""
  , "Use the keys \"h\", \"j\", \"k\", \"l\" to move around like:"
  , ""
  , "             k"
  , "             ^"
  , "         h <-+-> l"
  , "             v "
  , "             j"
  , ""
  , "We will take a closer look at movements later."
  , ""
  , "You can try out the commands here and later in "
  , "the editor."
  , ""
  , "This tutorial will focus particularly on the "
  , "structure behind the commands."
  , ""
  , "************************************************"
  , "************************************************"
  , ""
  , "# Modality"
  , ""
  , "Vim is a modal editor."
  , "This means the keybindings depend on the mode you "
  , "are currently in."
  , ""
  , "************************************************"
  , "## Normal mode"
  , ""
  , "command: \"ESC\""
  , ""
  , "As the starting point in Normal mode keyboard input "
  , "is written to the command-line below."
  , "Commands are directly executed if valid."
  , ""
  , "The training wheels help you see the command-line."
  , ""
  , "While in vim an \"i\" will always start insert mode,"
  , "With training wheels, the command needs to be the "
  , "only string on the command-line to be valid. "
  , ""
  , "************************************************"
  , "## Insert mode"
  , ""
  , "command: \"i\""
  , ""
  , "For writing new text Insert mode is needed. "
  , "Focus lies on the text, and it can be directly"
  , "edited. There are more commands to start Insert mode"
  , "command: \"a\" start Insert mode after the cursor"
  , "command: \"A\" start Insert mode at the end of the line."
  , ""
  , "Use \"Esc\" to get back to Normal mode."
  , ""
  , "************************************************"
  , "## Visual mode"
  , ""
  , "command: \"v\""
  , ""
  , "Some commands require a selection as input. In "
  , "Visual mode the selections are visual. For example, to"
  , "be sure you delete the next two words in "
  , "the selection can be made in Visual mode"
  , "to then apply a command."
  , ""
  , "Selections use the same keybindings as movements."
  , ""
  , "Use \"Esc\" to clear the command-line and get back "
  , "to Normal mode."
  , ""
  , "************************************************"
  , "## Command mode"
  , ""
  , "command: \":\""
  , ""
  , "Exit the editor, save the file, or toggle help, all"
  , "need Command mode. "
  , ""
  , "Commands will only be executed after using  \"Enter\"."
  , ""
  , "In Vim Command mode is mostly invisible. The wheels"
  , "help you see it. There are also other commands in"
  , "Vim not starting with \":\" but the training wheels"
  , "don't support those commands."
  , ""
  , "Use \"Esc\" to clear the command-line and get back"
  , "to Normal mode"
  , ""
  , "************************************************"
  , "************************************************"
  , ""
  , "# Direct Commands"
  , ""
  , "Some commands don't need further input. But they "
  , "can be repeated."
  , ""
  , "┌───────┐   ┌─────────┐"
  , "│ count │ + │ command │"
  , "└───────┘   └─────────┘"
  , ""
  , "For example use \"7j\" to execute \"j\" 7 times."
  , "Most commands can be used more efficiently when "
  , "combined with a count."
  , ""
  , "************************************************"
  , "************************************************"
  , ""
  , "# Operator Commands "
  , ""
  , "Some commands need further input like a motion."
  , ""
  , "┌───────┐   ┌─────────┐   ┌────────┐"
  , "│ count │ + │ command │ + │ motion │ "
  , "└───────┘   └─────────┘   └────────┘"
  , ""
  , "For example \"y\", yank, which copies the selection"
  , "to a clipboard."
  , ""
  , "************************************************"
  , "************************************************"
  , ""
  , "That's it for the main concept. "
  , ""
  , "1. Keybindings depend on the mode you are in."
  , ""
  , "2. Commands can be used like building blocks for "
  , "   more efficient usage."
  , ""
  , "Let's move on to the different commands."
  , "Many of them can be remembered by the first "
  , "letter of a verb describing their action."
  , "************************************************"
  , "************************************************"
  , ""
  , "# Command-line commands"
  , ""
  , "Let's first look at how you can exit the editor "
  , "and safe the file."
  , ""
  , "\":w\" -> write to file which means saving it"
  , ""
  , "\":q\" -> quit the program"
  , ""
  , "\":wq\" -> write to file then quit the program"
  , ""
  , "************************************************"
  , "************************************************"
  , ""
  , "# Movements or Selection"
  , ""
  , "             k"
  , "             ^"
  , "         h <-+-> l"
  , "             v "
  , "             j"
  , ""
  , "As shown before the above keys are used to move "
  , "around, but we can be even more efficient:"
  , ""
  , "\"b\" -> move to the beginning of the word "
  , "       instead of \"h\" moving left by character"
  , "       we can move left by word."
  , ""
  , "\"e\" -> move to end of word."
  , "       move to the right by word"
  , "    "
  , "\"0\" -> move to the beginning of the line"
  , ""
  , "\"$\" -> move to the end of the line"
  , ""
  , "Movements can also be used as motions for"
  , "commands and as selections in visual mode."
  , ""
  , "************************************************"
  , "************************************************"
  , ""
  , "# Meet your new best friend"
  , ""
  , "Before you edit this tutorial's text by mistake, "
  , "take a look at a vim-beginners best friend"
  , ""
  , "                       "
  , "          ****   ****      "
  , "       ***   ** **   ***   "
  , "      **       *       **  "
  , "      *                 *  "
  , "      **      undo     **  "
  , "        **           **    "
  , "          ***     ***      "
  , "             ** **         "
  , "               *   "
  , ""
  , "\"u\" -> undo last edit"
  , "\"Ctrl-r\" -> redo the undo"
  , ""
  , "Whatever happens, undo is there to take you back"
  , "to the good old times."
  , ""
  , "************************************************"
  , "************************************************"
  , ""
  , "# Edit text"
  , ""
  , "\"x\" -> delete the current character and copy it "
  , "       to the clipboard"
  , "\"p\" -> put the clipboard contents after the cursor"
  , ""
  , "\"d\" + motion -> delete the selected and copy it "
  , "                to the clipboard"
  , "\"dd\" -> delete the whole line"
  , ""
  , "\"y\" + motion -> yank the selected, which means "
  , "                copy it to the clipboard"
  , ""
  , "\"yy\" -> yank the whole line"
  , ""
  , "************************************************"
  , "************************************************"
  , ""
  , "Unfortunately, the training wheels don't support "
  , "all Vim commands and functionality, but hopefully"
  , "they helped you get some comfort with using modes"
  , "and only the keyboard for editing text."
  , ""
  , "************************************************"
  , "************************************************"
  ]
