name: Update Documentation Graph

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.8'
        enable-stack: true
        stack-version: latest
        

    - name: Cache Stack
      uses: actions/cache@v3
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-stack-


    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y graphviz
      
    - name: Install graphmod
      run: stack build --copy-compiler-tool graphmod
      
    - name: Generate module graph
      run: stack exec graphmod | tred | dot -Tpng > Documentation/modules.png
