name: Update Documentation Graph

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-haskell@v1
      with:
        enable-stack: true
        stack-version: latest
        

    - name: Cache Stack
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y graphviz

    - name: Generate module graph
      run: stack exec graphmod | tred | dot -Tpng > Documentation/modules.png
